// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAN5FcrzaMd9Obo5az80lkV5vurxiA5Fss',
    appId: '1:829796413226:web:0df67356ed5e4d18337853',
    messagingSenderId: '829796413226',
    projectId: 'poikatsu-app-73257',
    authDomain: 'poikatsu-app-73257.firebaseapp.com',
    storageBucket: 'poikatsu-app-73257.firebasestorage.app',
    measurementId: 'G-40Z4XD0XEM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAj87Lm70ZF7SiPcv2YyeqDCeDGBMeKopI',
    appId: '1:829796413226:android:c1fa23cc4755336a337853',
    messagingSenderId: '829796413226',
    projectId: 'poikatsu-app-73257',
    storageBucket: 'poikatsu-app-73257.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkaoR6sltBnl81XDAeKbxlm8w8cCUc6Cc',
    appId: '1:829796413226:ios:08156f2c230dcd61337853',
    messagingSenderId: '829796413226',
    projectId: 'poikatsu-app-73257',
    storageBucket: 'poikatsu-app-73257.firebasestorage.app',
    iosBundleId: 'jp.keygo.poigo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkaoR6sltBnl81XDAeKbxlm8w8cCUc6Cc',
    appId: '1:829796413226:ios:08156f2c230dcd61337853',
    messagingSenderId: '829796413226',
    projectId: 'poikatsu-app-73257',
    storageBucket: 'poikatsu-app-73257.firebasestorage.app',
    iosBundleId: 'jp.keygo.poigo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAN5FcrzaMd9Obo5az80lkV5vurxiA5Fss',
    appId: '1:829796413226:web:d88e4274a44f1d25337853',
    messagingSenderId: '829796413226',
    projectId: 'poikatsu-app-73257',
    authDomain: 'poikatsu-app-73257.firebaseapp.com',
    storageBucket: 'poikatsu-app-73257.firebasestorage.app',
    measurementId: 'G-T3QNXH1F3N',
  );
}
